### Import Essential Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### Import DataSet

In [2]:
data = pd.read_csv('Data/data.csv')

In [3]:
data.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

### Drop date column

In [4]:
# data = data.drop('date', axis = 1)
data.drop('date', axis = 1, inplace = True)
data.head()

   precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

### Separate DataSet into Independent and Dependent Variable

In [5]:
X = data.iloc[:,:4].values
y = data.iloc[:,4].values

### Split DataSet into Training and Testing DataSet

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Apply Logistic Regression Algorithm

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

### Testing the Model

In [8]:
y_pred = model.predict(X_test)
y_pred

array(['sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain',
       'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'snow', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'snow', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain',
       'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun'], dtype=object)

### Create Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[  0,   0,   0,   0,  10],
       [  0,   0,   0,   0,  29],
       [  0,   0, 110,   0,  13],
       [  0,   0,   4,   2,   0],
       [  0,   0,   0,   0, 125]])

### Creation of Pickle File

In [10]:
import joblib
joblib.dump(model, '../../Model/Weather Prediction by Logistic Regression.pkl')
print('Model Saved Succesfully')

Model Saved Succesfully

### Checking the Accuracy of Model

In [11]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(acc*100, 2)}%')

Accuracy: 80.89%